---
- name: install versioneer
  pip: name="{{ item }}" executable=pip3
  with_items: [ versioneer markupsafe ]

- name: cleaning up dist
  local_action: file path={{ cif_build_sdist }}/dist state=absent

- name: build dist
  local_action: shell python3 setup.py sdist chdir={{ cif_build_sdist }}/

- name: find dist name
  local_action: find paths={{ cif_build_sdist }}/dist patterns="^(verbose-robot\-.*\.tar.gz)$" use_regex=True
  register: p

- name: upload dist and uarchive
  unarchive: src={{ p.files[0].path }} dest=/tmp

- name: find dist name
  find: paths=/tmp patterns="^(verbose-robot-.*)$" use_regex=True file_type=directory
  register: p

- name: set dist path
  set_fact: DIST_BUILD_PATH="{{ p.files[0].path }}"