---
- name: copy csirtg-fm rules
  command: cp -r "{{ DIST_BUILD_PATH }}/rules/" "{{ fm_rules_path | default(fm.rules_path) }}"

- name: Update rule permissions
  file:
    path: "{{ fm_rules_path | default(fm.rules_path) }}/default"
    mode: u=rwX,g=rwX,o=
    recurse: yes
    owner: "{{ fm_user | default(fm.user) }}"
    group: "{{ fm_group | default(fm.group) }}"