---

- name: systemd services
  template: src=fm/csirtg-fm.service.j2 dest=/etc/systemd/system/csirtg-fm.service owner=root group=root mode=0755

- name: enable services at boot
  systemd: name={{ item }} enabled=yes daemon_reload=yes state=started
  with_items:
    - csirtg-fm.service