---
- name: create FM_CIF_TOKEN
  shell: cat /dev/urandom | head -c 512 | shasum -a 256 | awk -F ' ' '{print $1}'
  register: cif_fm_token_generated
  when: FM_CIF_TOKEN is not defined or FM_CIF_TOKEN == ''

- set_fact:
    FM_CIF_TOKEN: "{{ cif_fm_token_generated.stdout }}"
  when: FM_CIF_TOKEN is not defined or FM_CIF_TOKEN == ''

- name: set FM token
  shell: cif-store --token-create-fm --token "{{ FM_CIF_TOKEN }}"