---
- name: create CIF_FM_TOKEN
  shell: cat /dev/urandom | head -c 512 | shasum -a 256 | awk -F ' ' '{print $1}'
  register: cif_fm_token_generated
  when: CIF_FM_TOKEN is not defined or CIF_FM_TOKEN == ''

- set_fact:
    CIF_TOKEN: "{{ cif_fm_token_generated.stdout }}"
  when: CIF_FM_TOKEN is not defined or CIF_FM_TOKEN == ''

- name: set FM token
  shell: cif-store --token-create-fm --token "{{ $CIF_FM_TOKEN }}"