---
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: tokens.yml
  tags: tokens

- import_tasks: paths.yml
  tags: paths

- import_tasks: services.yml
  when: ENABLE_SERVICES is defined and ENABLE_SERVICES == 'yes'
  tags: services
